import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useCurrentUser } from '../hooks/useCurrentUser';
import { db, ensureSettings, nowIso } from '../lib/db';
import { Card } from '../components/Card';

const themeOptions=['liquid','chrome','pink-chrome','dark-hero','amoled','aurora','cyber','cozy','sakura','minimal','space','forest'];
export default function OnboardingPage(){
 const {userId}=useCurrentUser();const nav=useNavigate();const [step,setStep]=useState(1);const [purpose,setPurpose]=useState('University');const [subjects,setSubjects]=useState('');const [goal,setGoal]=useState(180);const [theme,setTheme]=useState('liquid');
 const finish=async()=>{const now=nowIso();for(const name of subjects.split(',').map(x=>x.trim()).filter(Boolean)){await db.subjects.put({id:crypto.randomUUID(),userId,name,color:'#8a6cff',priority:1,archived:false,createdAt:now,updatedAt:now,syncStatus:'pending'});}await db.goals.add({id:crypto.randomUUID(),userId,type:'daily_time',target:goal,period:'daily',createdAt:now,updatedAt:now,syncStatus:'pending'});await ensureSettings(userId);await db.settings.update(userId,{themeId:theme,updatedAt:now});localStorage.setItem('studyflow.onboarded','1');localStorage.setItem('studyflow.studyPurpose',purpose);nav('/');};
 const skip=()=>{localStorage.setItem('studyflow.onboarded','1');nav('/');};
 return <div className="page" style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:20}}><Card className="hero-card" style={{width:'min(620px,100%)'}}><div className="eyebrow">Setup · {step}/5</div>{step===1&&<><h1>What are you studying for?</h1><div className="pill-row">{['School','University','Exam','Language','Personal'].map(x=><button key={x} className={`pill ${purpose===x?'active':''}`} onClick={()=>setPurpose(x)}>{x}</button>)}</div></>}{step===2&&<><h1>Add subjects</h1><p className="subtle">Separate multiple subjects with commas.</p><input className="input" value={subjects} onChange={e=>setSubjects(e.target.value)} placeholder="Physics, Math, Biology"/></>}{step===3&&<><h1>Daily goal</h1><input className="input" type="number" min="1" value={goal} onChange={e=>setGoal(Number(e.target.value)||1)}/><p className="subtle">minutes per day</p></>}{step===4&&<><h1>Choose a theme</h1><select className="input" value={theme} onChange={e=>setTheme(e.target.value)}>{themeOptions.map(x=><option key={x} value={x}>{x}</option>)}</select></>}{step===5&&<><h1>Ready to focus.</h1><p className="subtle">You can change everything later in Settings.</p></>}<div className="timer-actions" style={{marginTop:28}}><button className="button ghost" onClick={skip}>Skip</button>{step>1&&<button className="button" onClick={()=>setStep(x=>x-1)}>Back</button>}{step<5?<button className="button primary" onClick={()=>setStep(x=>x+1)}>Continue</button>:<button className="button primary" onClick={()=>void finish()}>Start studying</button>}</div></Card></div>;
}
