import { ChangeEvent, useRef, useState } from 'react';
import { useCurrentUser } from '../hooks/useCurrentUser';
import { useSettings } from '../hooks/useSettings';
import { db, nowIso } from '../lib/db';
import { Card } from '../components/Card';
import type { Exam, Goal, StudySession, StudyTask, Subject, Topic, UserSettings } from '../types';

const themes=[['plush','Plush Toy'],['liquid','Liquid'],['chrome','Chrome'],['pink-chrome','Pink Chrome'],['dark-hero','Dark Hero'],['amoled','AMOLED'],['aurora','Aurora'],['cyber','Cyber'],['cozy','Cozy Study'],['sakura','Sakura'],['minimal','Minimal'],['space','Space'],['forest','Forest']];
type Backup = {subjects?:Subject[];topics?:Topic[];tasks?:StudyTask[];sessions?:StudySession[];goals?:Goal[];exams?:Exam[];settings?:UserSettings};

export default function SettingsPage(){
 const {userId}=useCurrentUser(); const s=useSettings(userId); const fileRef=useRef<HTMLInputElement>(null); const [message,setMessage]=useState(''); if(!s)return <div className="page">Loading…</div>;
 const patch=async(p:Partial<UserSettings>)=>{await db.settings.update(userId,{...p,updatedAt:nowIso()});};
 const exportJson=async()=>{const payload={subjects:await db.subjects.where('userId').equals(userId).toArray(),topics:await db.topics.where('userId').equals(userId).toArray(),tasks:await db.tasks.where('userId').equals(userId).toArray(),sessions:await db.sessions.where('userId').equals(userId).toArray(),goals:await db.goals.where('userId').equals(userId).toArray(),exams:await db.exams.where('userId').equals(userId).toArray(),settings:s};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='studyflow-backup.json';a.click();URL.revokeObjectURL(a.href);};
 const exportCsv=async()=>{const sessions=await db.sessions.where('userId').equals(userId).toArray();const esc=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;const csv=['id,start_time,end_time,study_seconds,timer_type,subject_id',...sessions.map(x=>[x.id,x.startTime,x.endTime,x.studySeconds,x.timerType,x.subjectId??''].map(esc).join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='studyflow-sessions.csv';a.click();URL.revokeObjectURL(a.href);};
 const importBackup=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{const raw=JSON.parse(await f.text()) as Backup;const safety={subjects:await db.subjects.where('userId').equals(userId).toArray(),topics:await db.topics.where('userId').equals(userId).toArray(),tasks:await db.tasks.where('userId').equals(userId).toArray(),sessions:await db.sessions.where('userId').equals(userId).toArray(),goals:await db.goals.where('userId').equals(userId).toArray(),exams:await db.exams.where('userId').equals(userId).toArray()};localStorage.setItem('studyflow.lastSafetyBackup',JSON.stringify(safety));const assign=<T extends {userId:string;updatedAt:string;syncStatus?:string}>(rows:T[]|undefined)=>rows?.map(r=>({...r,userId,updatedAt:nowIso(),syncStatus:'pending'}));await db.transaction('rw',[db.subjects,db.topics,db.tasks,db.sessions,db.goals,db.exams],async()=>{if(raw.subjects)await db.subjects.bulkPut(assign(raw.subjects) as Subject[]);if(raw.topics)await db.topics.bulkPut(assign(raw.topics) as Topic[]);if(raw.tasks)await db.tasks.bulkPut(assign(raw.tasks) as StudyTask[]);if(raw.sessions)await db.sessions.bulkPut(assign(raw.sessions) as StudySession[]);if(raw.goals)await db.goals.bulkPut(assign(raw.goals) as Goal[]);if(raw.exams)await db.exams.bulkPut(assign(raw.exams) as Exam[]);});setMessage('Backup imported. A safety snapshot was stored locally before import.');}catch{setMessage('Import failed: invalid StudyFlow backup.');}finally{e.target.value='';}};
 const requestNotifications=async()=>{if(!('Notification'in window)){setMessage('Browser notifications are not supported here.');return;}const result=await Notification.requestPermission();setMessage(`Notification permission: ${result}`);};
 return <div className="page"><header className="page-header"><div><div className="eyebrow">Personalize</div><h1>Settings</h1></div></header><div className="grid grid-2"><Card><strong>Appearance & locale</strong><div className="form-row" style={{marginTop:16}}><label>Theme<select className="input" value={s.themeId} onChange={e=>void patch({themeId:e.target.value})}>{themes.map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label>Language<select className="input" value={s.language} onChange={e=>void patch({language:e.target.value as 'en'|'fa'})}><option value="en">English</option><option value="fa">فارسی</option></select></label><label>Calendar<select className="input" value={s.calendarType} onChange={e=>void patch({calendarType:e.target.value as 'gregorian'|'jalali'})}><option value="gregorian">Gregorian</option><option value="jalali">Jalali / Persian</option></select></label><label>Number format<select className="input" value={s.numberFormat} onChange={e=>void patch({numberFormat:e.target.value as 'latin'|'persian'})}><option value="latin">123</option><option value="persian">۱۲۳</option></select></label><label>Week starts<select className="input" value={s.weekStart} onChange={e=>void patch({weekStart:e.target.value as 'saturday'|'sunday'|'monday'})}><option value="saturday">Saturday</option><option value="sunday">Sunday</option><option value="monday">Monday</option></select></label><label><input type="checkbox" checked={s.reduceMotion} onChange={e=>void patch({reduceMotion:e.target.checked})}/> Reduce motion</label></div></Card>
 <Card><strong>Pomodoro</strong><div className="form-row" style={{marginTop:16}}><label>Focus minutes<input className="input" type="number" value={s.pomodoroFocus} onChange={e=>void patch({pomodoroFocus:Number(e.target.value)})}/></label><label>Short break<input className="input" type="number" value={s.pomodoroShortBreak} onChange={e=>void patch({pomodoroShortBreak:Number(e.target.value)})}/></label><label>Long break<input className="input" type="number" value={s.pomodoroLongBreak} onChange={e=>void patch({pomodoroLongBreak:Number(e.target.value)})}/></label></div></Card>
 <Card><strong>Preferences</strong><div className="form-row" style={{marginTop:16}}><label><input type="checkbox" checked={s.notifications} onChange={e=>void patch({notifications:e.target.checked})}/> Notifications</label><button className="button" onClick={()=>void requestNotifications()}>Request notification permission</button><label><input type="checkbox" checked={s.haptics} onChange={e=>void patch({haptics:e.target.checked})}/> Haptics</label><label><input type="checkbox" checked={s.sounds} onChange={e=>void patch({sounds:e.target.checked})}/> Focus sounds preference</label></div></Card>
 <Card><strong>Data & backup</strong><p className="subtle">JSON contains the full local StudyFlow dataset. CSV exports study sessions. Import creates a local safety snapshot before merging records.</p><div className="pill-row"><button className="button" onClick={()=>void exportJson()}>Export JSON</button><button className="button" onClick={()=>void exportCsv()}>Export CSV</button><button className="button" onClick={()=>fileRef.current?.click()}>Import JSON</button></div><input ref={fileRef} type="file" accept="application/json" hidden onChange={e=>void importBackup(e)}/>{message&&<p className="subtle">{message}</p>}</Card></div></div>;
}
